---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-vip/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./namespace.yaml
#  - ./nfs-subdir-external-provisioner/ks.yaml
  - ./reloader/ks.yaml
