apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3XJJzHnWxLIpYOnWZwfmsqwHjuiRmJFA,iv:VgtafXgsAs7EATybI1lugCgTH5EfJ/b0BHwQJO8E7L8=,tag:23phQ7tStjSxPHQa/zJ5yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lgy9jptcf2zaewy5u8svcmvhzd7njgz0tr3hy6uh2el0sekx2ysqhzucr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVUpRS3E0OWM3ZldUT2xs
            OVZUSlptOVVsQ1hORC8zWmJicUZYc1UyNjM0CnpmVU5GZDkzb0RaSG9MMmxGNlNT
            azdqMkZSUkZMVFlaZFZQQU8yQUUzMlUKLS0tIDZqc1ZKQTBPeFB2SVRUUDhjQU11
            MW5OOWMyRjhxRHJhdzNBOFZEcGJySXcKAP5FjXhTHhI+pfUa31VJCFZwkEHtRlna
            Pyd8hJBU12c65zDHLeBdSi76OlltNkTJOwfMnxgkD9/KhMe/bggT+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-22T08:30:35Z"
    mac: ENC[AES256_GCM,data:OIJIfZBq7PnfXYQoSebgkVXBx9TGmkwZ/Qb2K5mt2ZbLKzn1DXtmGv/gYJtIj6IB2Vd+LhZp/0QuMNgnBZgzvG1TILsBJLaS1gr0xjE/5UH6xmuidY2xkuXxTMw77z9L+fw2Wcrvons2ztUNezomsNxKvwTNXSfjIIDSe/FAXFk=,iv:DhCHxg4jum5IvzJ+B6Q6rRMfRW0CGkRk/dtb2qbbwZE=,tag:za28XivqSMOqyzqttw7I+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
