apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:TOcwboTH2JnZhyBBVE7LA5m8syK0ANw+AcwAT+XvmobnR1ir37lgtJ4AQBHVeak7kqNhogJQXsI4T7pf,iv:62gKODkFX7g9klTCNqhRWcQQGkY1ek2TxvyjiyyGfeM=,tag:VBlU4AGm71hADNfTaSBKzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lgy9jptcf2zaewy5u8svcmvhzd7njgz0tr3hy6uh2el0sekx2ysqhzucr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSFQyV0p4Zk9TYzY2Nldr
            SE5OWHNGOGM1TlhGYUFTbDExNDBEMnVMZWswCmRoVVVsSk9hNmNUY1ozMWt6VWph
            MWZSc254TG9lT0EweStyY1h2a0xTVDQKLS0tIGFIU0JrWTIyTHBsK3pOaXVwcmwr
            ckpiazZvRXlaYWdEUFZzNjNTaUlOUFkKFRBrcK53KFc8AONj9vM8QLln3V9CU/fK
            Zo2PPHnd7HIQqO7dT0D/9swpYIrk66M27jlvKvidiqegHiENF439Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-22T08:30:35Z"
    mac: ENC[AES256_GCM,data:0DeGdPY+Xo2pMSPy3AoLLyFozDm7Lp9XhXOlBvNDDyAtqxFdvt4ylyldVph4uExOJf4GeeIl23bKuygYjz5uFcV1Nu9z8KhYvvzOJvm0wA9HPyashTw64mpoiK3aZnsOxnbJ7h3JFg55q1KQX6iebq9PlUBW1LENyZZyxi0lFmI=,iv:2v4tP/w7GQVYnO+TsOO2D7CcLVm7EtfvRx3MXYTHfJw=,tag:lc07Ijk1jFsR429e2LmHkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
