---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: &namespace kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: v4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    nfs:
      path: $NFS_PATH
      server: $NFS_SERVER
      mountOptions:
        - noatime
    storageClass:
      defaultClass: false
      pathPattern: "${.PVC.namespace}-${.PVC.name}"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nfs-subdir-external-provisioner
              topologyKey: kubernetes.io/hostname
